#!/usr/bin/expect

set user charles
set nas 132.208.13.62
set pass behappy
set green "\033\[0;32;40m"
set normal "\033\[0m"
#exp_internal 1
set timeout 20

spawn ssh -2 -s $user@$nas netconf

expect "password:"
send "$pass\r"
expect "<?xml version=\"1.0\" encoding=\"UTF-8\"?><hello><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:capability:writeable-running:1.0</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capability>urn:ietf:params:netconf:capability:url:1.0</capability><capability>urn:cisco:params:netconf:capability:notification:1.0</capability></capabilities><session-id>"
expect -re "(\d*)"
expect "</session-id></hello>]]>]]>" { puts " Matched Hello"}
puts "$green $expect_out(buffer) $normal"
#send "<?xml version=\"1.0\" encoding=\"UTF-8\"?><hello xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability></capabilities></hello>]]>]]>\r"
send "<?xml version='1.0' encoding='UTF-8'?><hello xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\"><capabilities><capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability><capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability><capability>urn:ietf:params:netconf:capability:validate:1.0</capability><capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability><capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</capability><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:liberouter:params:netconf:capability:power-control:1.0</capability><capability>urn:ietf:params:netconf:capability:candidate:1.0</capability><capability>urn:ietf:params:netconf:capability:xpath:1.0</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capability>urn:ietf:params:netconf:capability:interleave:1.0</capability></capabilities></hello>]]>]]>\r"

send_user "$green $expect_out(buffer) $normal"
#send "<?xml version=\"1.0\" encoding=\"UTF-8\" ?><rpc message-id=\"9.0\"><notification-on/></rpc>]]>]]>\r"
#expect "<?xml version=\"1.0\" encoding=\"UTF-8\"?><rpc-reply message-id=\"9.0\" xmlns=\"urn:ietf:params:netconf:base:1.0\"><ok/></rpc-reply>]]>]]>\r" { puts "Notification activeted\n"}
send_user "$green $expect_out(buffer) $normal"
sleep 1
puts "Ask for configuration\n"
# General
#send "<?xml version=\"1.0\" encoding=\"UTF-8\"?><rpc message-id=100><get-config><source><running/></source></get-config></rpc>]]>]]>\r"
                                           #"<rpc xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" message-id=\"urn:uuid:3dc370f4-039d-11e3-9552-525400123456\"><get-config><source><running /></source></get-config></rpc>"
send "<?xml version='1.0' encoding='UTF-8'?><rpc xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" message-id=\"urn:uuid:4bface2a-0397-11e3-8137-525400123456\"><get-config><source><running/></source></get-config></rpc>]]>]]>\r"
#send_user "$green $expect_out(buffer) $normal"
#Cisco
#send "<?xml version=\"1.0\" encoding=\"UTF-8\"?><rpc message-id=\"101\" xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\"><get-config><source><running/></source><filter><config-format-text-cmd><text-filter-spec> | inc interface </text-filter-spec></config-format-text-cmd></filter></get-config></rpc>]]>]]>\r"
#send "<?xml version='1.0' encoding='UTF-8'?><rpc xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" message-id=\"101\"><get-config><source><running/></source></get-config></rpc>]]>]]>\r"
#sleep 10
expect "<?xml version=\"1.0\" encoding=\"UTF-8\"?><rpc-reply message-id=\"101\" xmlns=\"urn:ietf:params:netconf:base:1.0\"><data><cli-config-data><cmd>interface FastEthernet0/0\r</cmd></cli-config-data></data></rpc-reply>]]>]]>\r" {
	puts "\nReceive OK\n"}

send_user "$green $expect_out(buffer) $normal"
#expect {
#	"rpc>]]>]]>\r" {
#		send_user "$green $expect_out(buffer) $normal"
#	}
#	"hello>]]>]]>\r" {
#		puts "Here"
#		send "<?xml version=\"1.0\" encoding=\"UTF-8\"?><hello xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability></capabilities></hello>]]>]]>\r"
#		send_user "$green $expect_out(buffer) $normal"
#		interact
#	}
#}
puts "\n"

exit 0

