#!/bin/bash

export SERVICE_ENDPOINT=http://127.0.0.1:35357/v2.0
export OS_AUTH_URL=$SERVICE_ENDPOINT
export OS_TENANT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=adminpwd
export OS_SERVICE_TOKEN='servicetkn'
